/// Dumps all pasteboard types and their values to help debug clipboard
/// integration with password managers and other apps that set special
/// pasteboard flags (e.g. org.nspasteboard.ConcealedType).
///
/// Usage:  Copy something, then run:
///   /usr/bin/swift tools/pb_debug.swift

import AppKit

let pb = NSPasteboard.general
print("Change count: \(pb.changeCount)")
print("Types on pasteboard:")
for type in pb.types ?? [] {
    let preview: String
    if let str = pb.string(forType: type) {
        preview = "string(\(str.prefix(40)))"
    } else if let data = pb.data(forType: type) {
        preview = "data(\(data.count) bytes)"
    } else {
        preview = "(present, no data)"
    }
    print("  \(type.rawValue) → \(preview)")
}

let concealedType = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
let autoGeneratedType = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
let transientType = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
let types = pb.types ?? []
print("\nConcealed?      \(types.contains(concealedType))")
print("AutoGenerated?  \(types.contains(autoGeneratedType))")
print("Transient?      \(types.contains(transientType))")
